import Head from "next/head";
import Main from "../../components/main/Main";
import About from "../../components/about/About";
import Skills from "../../components/skills/Skills";
import Projects from "../../components/projects/Projects";
import Contact from "../../components/contact/Contact";
export default function Home() {
  return (
    <>
      <Head>
        <title>Msoheil Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
